Setting up clang-format and clang-tidy
zephyrproject-rtos/gsoc-2022-thrift pull request #97
Opened 2022-06-23 11:47 UTC by SdtElectronics

This PR is still WIP.
Status:
- [x] Add `.clang-format` file to configure `clang-format`
- [x] Add `compile_flags.txt` file to configure `clang-tidy`
- [ ]  Create a new workflow for linting

2022-06-23 20:44 UTC, cfriedt requested changes
Looks like we may need a separate workflow for clang-tidy. I think that https://github.com/cpp-linter/cpp-linter-action might only be useful for wrapping around `clang-format` since it doesn't seem possible to include custom `CPPFLAGS` / `CXXFLAGS` for `clang-tidy` checks.

For `cpp-linter-action` with clang-format, I would suggest the following
* add a new `clang-format.yml` workflow
* if based on `cpp-linter-action`, specify
  * `tidy-checks: -*` (disable clang-tidy checking, that will go in a separate workflow)
  * `lines-changed-only`
  * `files-changed-only`
  
A separate `clang-tidy.yml` workflow should be relatively easy to do.

2022-06-24 07:36 UTC, cfriedt commented on .clang-format
> +---
Looks like scancode requires a license statement at the top of this file.

2022-06-24 12:05 UTC, SdtElectronics commented
> Looks like we may need a separate workflow for clang-tidy. I think that https://github.com/cpp-linter/cpp-linter-action might only be useful for wrapping around `clang-format` since it doesn't seem possible to include custom `CPPFLAGS` / `CXXFLAGS` for `clang-tidy` checks.
> 
> For `cpp-linter-action` with clang-format, I would suggest the following
> 
> * add a new `clang-format.yml` workflow
> * if based on `cpp-linter-action`, specify
>   
>   * `tidy-checks: -*` (disable clang-tidy checking, that will go in a separate workflow)
>   * `lines-changed-only`
>   * `files-changed-only`
> 
> A separate `clang-tidy.yml` workflow should be relatively easy to do.

`compile_flags.txt` serves the very purpose of providing compiler flags. It only supports setting flags for all files, though. Have gone through other `clang-tidy` actions in Github marketplace, I haven't find a single one supports passing flags as a parameter. We will have to customize a new workflow if we have more requirements on compiler flags.

A side note: `clang-tidy` supports designating flags for individual files, however, this is done with a compilation database, which is not meant to be handwritten, but generated by a build system. I tried using CMake to generate one for this project, but `clang-tidy` throws errors with that:
```
1 warning and 2 errors generated.
Error while processing /mnt/e/work_CS/embedded/zephyr-thrift-test/thrift-for-zephyr/lib/thrift/src/_stat.c.
error: unknown argument: '-fno-reorder-functions' [clang-diagnostic-error]
warning: optimization flag '-fno-defer-pop' is not supported [clang-diagnostic-ignored-optimization-argument]
/mnt/e/work_CS/embedded/zephyr-thrift-test/zephyr/lib/libc/newlib/include/stdint.h:15:10: error: 'newlib.h' file not found [clang-diagnostic-error]
#include <newlib.h>
         ^~~~~~~~~~
Found compiler error(s).
```

2022-06-24 16:17 UTC, cfriedt commented
@SdtElectronics - similarly, you will need to rebase and edit your commit messages so that they each include a `Fixes #<issue>` item.

This has the effect of implicitly linking a commit against an issue. When the commit is merged, the issue is automatically closed.

To edit your commit messages, do this:
```shell
git rebase -i --autosquash 7f83cf985bf0e097fe93cb0736a006251d14f90a
# substitute "pick" with "reword" or simply "r"
# exit
# reword each commit to include `Fixes #<issue>` on a separate line.
```

2022-06-26 03:25 UTC, SdtElectronics commented
CI failing due to `coding-style.sh` uses LGPL license. It is derived from the CERN Root project and the original license has to be preserved. On the other hand, this project doesn't depend on this script  to build or run, thus it should be fine to use it in a Apache 2.0 project.

2022-06-26 23:44 UTC, cfriedt commented on .github/workflows/coding-style.yml
> +      run: scripts/coding-style.sh
add a newline

2022-06-26 23:45 UTC, cfriedt commented on .github/workflows/coding-style.yml
> +      run: scripts/coding-style.sh
add a newline

2022-06-28 14:31 UTC, cfriedt commented on scripts/coding-style.sh
> +# SPDX-License-Identifier: LGPL-2.1-or-later
@SdtElectronics 
LGPL / GPL is incompatible with Apache-2.0 / Zephyr, so we can't use this script unfortunately.

I would suggest using this from upstream. It's Apache-2.0 licensed already 😁  Hopefully it works approximately the same

https://github.com/llvm/llvm-project/blob/c94a02e0e223bcce3b2c88741fae35d31a2d4f1d/clang/tools/clang-format/git-clang-format

2022-06-28 14:32 UTC, cfriedt requested changes
Update coding-style script to something permissively licensed.

2022-06-29 14:06 UTC, cfriedt commented on samples/lib/thrift/hello_server/src/main.cpp
> +  ::std::shared_ptr<HelloHandler> handler(new HelloHandler());
It looks as though it's much more common to use `std::` than `::std::` upstream. Let's stick with `std::` here.
```shell
cfriedt@cfriedt-mbp .upstream % grep -R "::std" * | wc -l
      65
cfriedt@cfriedt-mbp .upstream % grep -R "std" * | grep -v "::std" | wc -l
    8037
```

Looking much better already!

2022-06-29 14:08 UTC, cfriedt requested changes
replace of `::std::` with `std::`, for consistency

2022-06-29 14:55 UTC, merged